services:
  web:
    build: .
    container_name: web
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures file watching works in Docker
      - VITE_API_URL=/api
    networks:
      - challenge

networks:
  challenge:
    external: true
    name: challenge
